#Schema
dojo_config.settings:
  type: config_object
  label: 'Dojo Config Settings'
  mapping:
    newsletter:
      type: mapping
      label: 'Newsletter settings'
      mapping:
        subject:
          type: string
          label: 'Subject'
        default_from_email:
          type: email
          label: 'Default From Email'
        active:
          type: boolean
          label: 'If the newsletter is active or not'
        periodicity:
          type: string
          label: 'How often the newsletter is sent (daily, weekly or monthly)'
        news_number:
          type: integer
          label: 'Number of news to include in each newsletter'
